"""initial missing person hub schema

Revision ID: 27a3d918d44c
Revises: 
Create Date: 2026-08-27 07:35:02.677443
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '27a3d918d44c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mp_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_admins_username'), 'mp_admins', ['username'], unique=True)
    op.create_table('mp_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_audit_logs_action'), 'mp_audit_logs', ['action'], unique=False)
    op.create_table('mp_disasters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('disaster_type', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('affected_locations', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_disasters_active'), 'mp_disasters', ['active'], unique=False)
    op.create_index(op.f('ix_mp_disasters_code'), 'mp_disasters', ['code'], unique=True)
    op.create_table('mp_discovery_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['mp_disasters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disaster_id', 'url', name='uq_mp_discovery_event_url')
    )
    op.create_index(op.f('ix_mp_discovery_candidates_disaster_id'), 'mp_discovery_candidates', ['disaster_id'], unique=False)
    op.create_index(op.f('ix_mp_discovery_candidates_platform'), 'mp_discovery_candidates', ['platform'], unique=False)
    op.create_index(op.f('ix_mp_discovery_candidates_status'), 'mp_discovery_candidates', ['status'], unique=False)
    op.create_table('mp_missing_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=60), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_ne', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('residential_address_private', sa.Text(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('last_seen_time', sa.Time(), nullable=True),
    sa.Column('last_seen_location', sa.Text(), nullable=False),
    sa.Column('clothing', sa.Text(), nullable=True),
    sa.Column('identification_details', sa.Text(), nullable=True),
    sa.Column('public_contact_number', sa.String(length=80), nullable=True),
    sa.Column('private_contact_number', sa.String(length=80), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['mp_disasters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_missing_people_archived'), 'mp_missing_people', ['archived'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_case_number'), 'mp_missing_people', ['case_number'], unique=True)
    op.create_index(op.f('ix_mp_missing_people_disaster_id'), 'mp_missing_people', ['disaster_id'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_last_seen_date'), 'mp_missing_people', ['last_seen_date'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_last_seen_location'), 'mp_missing_people', ['last_seen_location'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_name'), 'mp_missing_people', ['name'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_name_ne'), 'mp_missing_people', ['name_ne'], unique=False)
    op.create_index(op.f('ix_mp_missing_people_published'), 'mp_missing_people', ['published'], unique=False)
    op.create_table('mp_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['mp_missing_people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'url', name='uq_mp_source_person_url')
    )
    op.create_index(op.f('ix_mp_sources_person_id'), 'mp_sources', ['person_id'], unique=False)
    op.create_index(op.f('ix_mp_sources_platform'), 'mp_sources', ['platform'], unique=False)
    op.create_table('mp_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disaster_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_ne', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('residential_address_private', sa.Text(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('last_seen_time', sa.Time(), nullable=True),
    sa.Column('last_seen_location', sa.Text(), nullable=True),
    sa.Column('clothing', sa.Text(), nullable=True),
    sa.Column('identification_details', sa.Text(), nullable=True),
    sa.Column('public_contact_number', sa.String(length=80), nullable=True),
    sa.Column('reporter_name_private', sa.String(length=255), nullable=True),
    sa.Column('reporter_phone_private', sa.String(length=80), nullable=True),
    sa.Column('reporter_relationship', sa.String(length=100), nullable=True),
    sa.Column('social_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['mp_disasters.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['mp_missing_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mp_submissions_disaster_id'), 'mp_submissions', ['disaster_id'], unique=False)
    op.create_index(op.f('ix_mp_submissions_status'), 'mp_submissions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mp_submissions_status'), table_name='mp_submissions')
    op.drop_index(op.f('ix_mp_submissions_disaster_id'), table_name='mp_submissions')
    op.drop_table('mp_submissions')
    op.drop_index(op.f('ix_mp_sources_platform'), table_name='mp_sources')
    op.drop_index(op.f('ix_mp_sources_person_id'), table_name='mp_sources')
    op.drop_table('mp_sources')
    op.drop_index(op.f('ix_mp_missing_people_published'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_name_ne'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_name'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_last_seen_location'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_last_seen_date'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_disaster_id'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_case_number'), table_name='mp_missing_people')
    op.drop_index(op.f('ix_mp_missing_people_archived'), table_name='mp_missing_people')
    op.drop_table('mp_missing_people')
    op.drop_index(op.f('ix_mp_discovery_candidates_status'), table_name='mp_discovery_candidates')
    op.drop_index(op.f('ix_mp_discovery_candidates_platform'), table_name='mp_discovery_candidates')
    op.drop_index(op.f('ix_mp_discovery_candidates_disaster_id'), table_name='mp_discovery_candidates')
    op.drop_table('mp_discovery_candidates')
    op.drop_index(op.f('ix_mp_disasters_code'), table_name='mp_disasters')
    op.drop_index(op.f('ix_mp_disasters_active'), table_name='mp_disasters')
    op.drop_table('mp_disasters')
    op.drop_index(op.f('ix_mp_audit_logs_action'), table_name='mp_audit_logs')
    op.drop_table('mp_audit_logs')
    op.drop_index(op.f('ix_mp_admins_username'), table_name='mp_admins')
    op.drop_table('mp_admins')
    # ### end Alembic commands ###
